spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${mysql.password}
    url: ${mysql.url}
    username: ${mysql.username}
  jpa:
    database: sql-server
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    show-sql: true
  config:
    import: env.yml
